name: MERN CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    

    - name: Build backend
      working-directory: ./backend
      run: |
        npm ci
        npm install -g nodemon
        
        # Start server in background and check health
        (npm run start &)
        timeout 120 bash -c 'until curl --silent --output /dev/null http://localhost:5000/api/health; do sleep 2; done'
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: |
        npm ci --legacy-peer-deps --prefer-offline    
    - name: Build frontend
      working-directory: ./frontend
      env:
        CI: false
      run: |
        npm run build


